hmcts/courtfinder-search

courtfinder/settings/base.py, uwsgi.conf
Set the chdir option in uwsgi.conf to the correct root directory, and
changed the DEBUG setting to True in base.py as it was previously
set to such in local.py (which was removed).
=> Fix mistakes in uwsgi config from introduced in previous refactoring

courtfinder/apps/healthcheck/urls.py, courtfinder/apps/healthcheck/views.py, requirements/base.txt
[django-moj-irat](https://github.com/ministryofjustice/django-moj-irat) offers a ready-made, well-tested `ping.json` implementation that behaves in the way we want (using environment variables to provide its values), so we should use that instead of maintaining our own.
This depends on ministryofjustice/django-moj-irat#4, which adds support for Python 2.7.
For this to behave as intended, we need `APP_BUILD_DATE`, `APP_GIT_COMMIT`, `APP_BUILD_TAG`, and `APP_VERSION` environment variables to be appropriately set.
=> Use standard ping.json from django-moj-irat

shippable.yml
otherwise it returns false negative for builds in branches other than master and develop.
=> Make shippable build all the branches,

Dockerfile, courtfinder/settings/production.py
Currently environment variables are hard coded, this change means that
we can pass them in.
* Use database DB_ environment variables if they exist
* Use COURTFINDER_ADMIN_HEALTHCHECK_URL from environment if exists
* Use COURTS_DATA_S3_URL from environment if exists
* Make sure RAILS_ENV=production in Dockerfile
=> Set environment variables

courtfinder/test_utils.py
populate-db now requires options to be passed such as --load-remote
or --ingest, this change updates the test calls to reflect this
change.
=> Fix test utils call to populate-db

courtfinder/apps/search/management/commands/populate-db.py, data/import-utilities/ingest-json.sh
For some invocations we require sys exits, but we also need the script
to conform to django command standards for testing. This change will
make the script usage accessible when passed the --script parameter.
=> Make populate-db callable as a script or functions

courtfinder/apps/search/management/commands/populate-db.py, courtfinder/test_utils.py
This change allows us to specify a directory on the command line,
which is required when we pass in testing data.
=> Allow passing courts data directory to populate-db

courtfinder/apps/search/ingest.py, courtfinder/apps/search/management/commands/populate-db.py, courtfinder/settings/base.py, courtfinder/settings/production.py, data/import-utilities/ingest-json.sh
Implement multiple database support for courts.json data ingestion
Currently, calling ingest will always load the courts data into the default
database. When importing data, we want to import it into a temporary
database, and then swap this with the live one.
This change allows the --database parameter to be passed to the
populate-db script, and so the Ingest, which uses the identifier
to get/create/save objects to the matching database entry in the django settings file.
(Closes #122)
=> Implement multiple database support for courts.json data ingestion

courtfinder/apps/search/templates/search/results.jinja, courtfinder/apps/search/tests/test_search.py
Display request to do separating parents survey on the search results page for users who have chosen 'children', 'divorce', 'domestic abuse' as the area of law.
=> Add a survey request to top of search results

courtfinder/apps/search/templates/search/results.jinja
Display request to do separating parents survey on the search results page for users who have chosen 'children', 'divorce', 'domestic abuse' as the area of law.
Compare lowercase area of law text in condition to ensure match occurs ignoring case.
=> Fix condition used in check whether to show survey

courtfinder/staticpages/forms.py, courtfinder/staticpages/templates/staticpages/feedback.jinja, courtfinder/staticpages/tests.py, courtfinder/staticpages/views.py, requirements/base.txt
To prevent feedback form spam I've added a rate limiter to the feedback post method which limits the requests to 3 per hour.  The rate limiter currently only limits on IP address, so we'll have to see if this is sufficient to prevent the spammer.
As an additional measure I've added a hidden honey pot field which needs to remain empty for the feedback form to be valid. 
If the rate limiter is triggered, or data is inputed into the honey pot field, the user will still see the feedback confirmation page, but no email will be sent.
=> Added rate limiting and a honeypot field to the feedback form

courtfinder/search/management/commands/populate-db.py, data/import-utilities/ingest-json.sh
Since we exit 0 on no change in courts, the script interprets this as
needing to ingest courts. This change adds the exit code 200 to signify
no changes, and so the script can exit gracefully without importing any
data.
=> Fix always ingesting courts data

data/import-utilities/ingest-json.sh
This change ensures we test the correct exit code from the populate-db
command.
=> Fix testing the correct exit code

courtfinder/assets-src/stylesheets/styles.scss, courtfinder/search/court_search.py, courtfinder/search/templates/search/results.jinja, courtfinder/search/tests/test_search.py, courtfinder/search/views.py, data/test_data/courts.json
No migration in this change
Tests included/updated
This change redirects a user to a closed court if they specifically search for it in the "Court Name or Address" section.
Result count logic amended to work with the new change
=> CF-109 Include closed courts in search results

courtfinder/courts/templates/courts/court.jinja, courtfinder/courts/tests.py, courtfinder/courts/views.py, courtfinder/search/ingest.py, courtfinder/search/migrations/0010_court_hide_aols.py, courtfinder/search/models.py, courtfinder/search/templates/search/results.jinja, courtfinder/search/tests/test_search.py, courtfinder/search/views.py, data/test_data/courts.json
For some courts the AoLs need to be hidden so the user does not think they can turn up to the court.
Includes a migration.
=> CF-105 - Hide AoLs

data/import-utilities/ingest-json.sh
Ingestion runs in two stages, loading the remote courts data into the application,
and then importing it into the database. If the first stage is successful but the
second fails, there will only be one warning then the application will stop warning.
This change ensures that it retries and also keeps warning.
=> Add a marker file that indicates if last data import successful

courtfinder/search/court_search.py
Investigating with sentry revealed the below error:
```
SSLErrorrequests.adapters in send
errorhostname 'mapit.mysociety.org' doesn't match either of '2014.mysociety.org', '2015.mysociety.org', '2016.mysociety.org', 'blog.fixmytransport.com', 'blogs.mysociety.org', 'cee.mysociety.org', 'diy.mysociety.org', 'mysociety.co.uk', 'mzalendo.com', 'news.mysociety.org', 'pombola.co.uk', 'pombola.com', 'pombola.org', 'pombola.org.uk', 'pombola.uk', 'scenic.mysociety.org', 'www.mysociety.co.uk', 'www.mysociety.org', 'www.mzalendo.com', 'www.pombola.co.uk', 'www.pombola.com', 'www.pombola.org', 'www.pombola.org.uk', 'www.pombola.uk'
```
=> Temporary workaround to mapit SSL issues.

courtfinder/courtfinder/settings/base.py, requirements/base.txt
This way, the necessary packages are installed to make verifiable SSL requests.
This is a better way of fixing #163.
=> Install security variant of requests, switch to HTTPS

courtfinder/courts/templates/courts/court.jinja
Fix to stop empty strings displaying in markup
=> Hotfix for empty brackets under court contacts

courtfinder/courts/templates/courts/leaflets/_info.jinja, courtfinder/courts/templates/courts/leaflets/defence/_info.jinja, courtfinder/courts/templates/courts/leaflets/defence_leaflet.jinja, courtfinder/courts/templates/courts/leaflets/juror/_info.jinja, courtfinder/courts/templates/courts/leaflets/prosecution/_info.jinja
The text fields used for additional information for each leaflet are now rich edit fields.
Path changed in defence leaflet to point at the correct folder.
=> CF-102 Allow leaflets to use raw html

courtfinder/search/migrations/0014_merge.py
Django migrations were created in parallel git branches. This fix is the result of 'manage.py makemigrations --merge' which merges the django migrations together prevents migrate from asking for user input, necessary for successful jenkins deployments.
=> Merged Dajngo migrations

courtfinder/search/management/commands/populate-db.py, vagrant/bootstrap.sh
The Vagrant bootstrapping was not working correctly. I have got it
working by basing it on the Dockerfile setup that is working correctly.
- Debian dependencies changed to match the Dockerfile. Dependencies that
are not from the Dockerfile are pulled out separately to make the
intent clear.
- Fixed the .bashrc was being updated to make it idempotent.
- Pin setuptools to version 32 to avoid a race condition (see:
https://github.com/pypa/setuptools/issues/951#issuecomment-278933232)
- Fix postgres setup to make it idempotent.
- Fix frontend dependency install (this was broken because an incorrect
version of node was being used, fixing the debian dependencies fixed
this).
Variable used before being defined. This code was rearranged to fail
early (good) but in doing so this error log was made …
=> Fix vagrant setup

courtfinder/courts/views.py
If the `COURT_IMAGE_BASE_URL` or court `image_file` are `None` a
`TypeError` is thrown.
=> Fix bug in #186

courtfinder/courtfinder/settings/base.py, courtfinder/courts/templates/courts/court.jinja, courtfinder/courts/tests.py, courtfinder/courts/views.py
Before this change the leaflets markup had been commented out in the
template but the tests had not been commented out so some tests were
failing. This change introduces a feature flag that is switched off and
puts the markup behind that feature flag.
The tests now explicitly enable the feature flag and there are two new
tests verifying that the feature flag properly hides the leaflets
section.
When we come to enable leaflets we can now just enable the flag
in the environment we're interested in and then in production.
=> Put leaflets behind a feature flag

Dockerfile, docker/run.sh, docker/setup_npm.sh
We noticed that migrations are not being run when an app is deployed. Investigating pointed us towards commit 8496ce1 which uses a `run.sh` that doesn't respect the `DOCKER_STATE` environment variable.
I haven't been able to tie this back to a pull request. It looks like there was a large history change at some point in the past that this was involved in.
Further investigation revealed that the Dockerfile seems to be more complicated than is necessary.
This change strips down and fixes the Dockerfile in a number of ways:
- Remove pip install uWSGI as the dependency is already in
requirements.txt
- Simplify how the code is copied into place.
- Use the main `run.sh` which includes the `DOCKER_STATE` commands.
- Generate assets in place rather than doing so in a site directory …
=> Simplify and fix Dockerfile

courtfinder/search/court_search.py, courtfinder/search/tests/test_search.py
MapIt have recently introduced harsher rate limits on their API. This highlighted the fact that we're calling the MapIt API quite a lot in our tests. This change mocks out calls to MapIt so that we don't get hit by the rate limit and get much faster test runs.
=> Remove test dependency on mapit

courtfinder/search/court_search.py, courtfinder/search/tests/test_search.py, data/test_data/courts.json
This adds two tests around the `CourtSearch.__postcode_search` method as a safety net for changing the implementation.
- One test to verify postcode prefix searches are working as expected.
- One test to verify that filtering by area of law is working as expected.
The intention of this change is to simplify and generally improve the postcode search.
The previous solution uses a rather complex raw query and an even more complex deduping approach (apparently for some marginal performance improvements). Given the effort placed on performance here I have assumed that there can be quite a lot of courts returned. I've tried to address that in a few of ways.
1. Replace the raw SQL with a Django ORM based query
This means that we can more easily join through the courts table to get the areas of …
=> Simplify basic postcode search

.travis.yml, Dockerfile, apt/base.sh, apt/development.sh, apt/production.sh, apt/testing.sh, docker/setup_npm.sh, vagrant/bootstrap.sh
Add a Travis config file so that we can easily run tests against each new branch.
This change also extracts apt dependencies into separate scripts. The travis config was the third place that needs to install the same set of dependencies (Docker, vagrant bootstrapping, and now travis). I've pulled the dependencies out into three classes; basic build dependencies, development dependencies and test dependencies.
`npm` and `nodejs` are split out into a separate file and not installed on travis because travis already provides both and apt fails if we try to install them again. I have taken the opportunity to upgrade to the more recent `nodejs` package (`nodejs` rather than `nodejs-legacy`). This requires a symlink from the expected name of `node` to allow gulp to work.
=> Add Travis config file

courtfinder/assets-src/stylesheets/leaflet-print.scss, courtfinder/assets-src/stylesheets/styles.scss, courtfinder/courts/templates/courts/court.jinja
Hat-tip to Leo who provided the CSS.
I came across it because I was looking for styles relating to facilities.
This fixes a display issue where `&nbsp;` is getting displayed on the page. The facilities descriptions are safe because they are managed by staff and tags have already been stripped from the content.
=> RST-216 fix facilities text wrapping

courtfinder/courtfinder/settings/base.py, courtfinder/search/court_search.py, courtfinder/search/tests/test_postcode.py
MapIt returns the quota and current usage as response headers. This change logs both numbers and also the calculated percentage we are through the quota. Ultimately this will need to be in some monitoring system. Until we know what the best system is it can go here.
This PR also includes simplifying logging config and adding a Sentry handler.
I've simplified the logging config because when deployed the only logs that get shipped are those coming out on stdout and stderr so writing a bunch of different logs to different log files isn't much help.
=> Mapit usage tracking

courtfinder/courtfinder/settings/base.py, courtfinder/search/court_search.py, courtfinder/search/tests/test_postcode.py
The mapit usage tracking was not being logged and even if it was it
wasn't going to be very easy to use for a sensu alert. This commit
introduces a few changes to make that easier.
- Introduce a new deafult handler that logs to stdout
- Introduce a custom json handler
- Remove response text from mapit error logging, the response is long
and multiline so messes up the logs for little value
- Make mapit usage logging json. This allows us to more easily add a
sensu check.
=> RST-223 Improve Mapit usage tracking

courtfinder/core/middleware.py, courtfinder/courtfinder/settings/test.py, courtfinder/search/tests/test_search.py
If we use the field names indexed by ELK it allows us to do more complex searches and filters. It also allows us to more easily query across different sources.
Logging in tests clouds the output and makes it harder to read. This also removes a leftover print statement.
=> Improve logging

courtfinder/courts/templates/courts/court.jinja, courtfinder/courts/templates/courts/leaflets/juror/_travel.jinja
This fix prevents maps of Tuscany being offered to users of courts that have lost their latitude or longitude values and are not otherwise filtered. This is only a partial fix; the admin app should probably not allow a null  lat / long to be exported.
=> Fixed: Don't display map if lat or lon is null

.travis.yml
Travis is failing to install gulp because npm is missing. Installing Node.js will solve this issue.
It will be used the same nodejs version with production.
=> Add node.js in Travis config

.travis.yml
https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch
This is a short term fix to allow work to continue on courtfinder-search
while we figure out how to fix it properly.
=> Use previous travis build version

courtfinder/courts/templates/courts/court.jinja, courtfinder/courts/tests.py
RST-361 As a juror I would like to access information on jury service, so that I can find out more about the task that I will be doing.
=> Add 'About jury service' link to Crown Court pages

docker/setup_npm.sh, package.json
Chalk is being pulled in as an unrestricted dependency. It looks like
Chalk version 2.0.0 went to ES6 which now causes it to break on our
build. This change pins it to the most recent version before 2.0.0.
It also checks that /usr/bin/node doesn't exist before trying to symlink
it so that `setup_npm.sh` can be used more easily from vagrant.
=> Pin npm dependency chalk to 1.1.3

courtfinder/search/court_search.py, courtfinder/search/tests/test_search.py
It still isn't clear how the user managed to get to a URL with the area of law in lowecase but this change will mean that if it happens again the URL will work.
=> RST-406 case insensitive area of law

Dockerfile, docker/setup_npm.sh, package.json, vagrant/bootstrap.sh
This change moves away from installing gulp globally and instead runs gulp through npm. This means that the version of gulp is under the control of the package.json and not floating free.
=> Run gulp through npm

.travis.yml, docker/setup_npm.sh, vagrant/bootstrap.sh
http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3422_28_march_2016
sass 3.4.22 dropped support for Ruby 1.8 and 1.9.
Given that this is a Python project and we don't need any of the newer
features of sass it seems simplest to pin sass to the latest version
that supports the default Ruby version for ubuntu.
=> Pin sass gem to 3.4.21

.dockerignore, Dockerfile, apt/base.sh
Reduce the size of the built image by ignoring files and directories from the build context.
The standard python base image is almost 700MB. This change reduces the size of the built image by using the slim base image and adding just the dependencies we need.
There are a number of other changes to the Dockerfile to reduce the size of the image.
- Combine the `apt/production.sh` and asset building stages so that the asset building dependencies can be removed without ever getting commited to a layer.
- Remove the `node_modules`, asset building apt dependencies and apt lists
in the system dependencies / asset building stage.
- Do not use the cache when installing python dependencies.
Together these changes reduce the image size from 1.56GB to 784MB
=> Rst 416 reduce size of docker image

Dockerfile.dev, docker-compose.yml
The docker version on the build environment is pre-1.9 and therefore
does not understand the `ARG` command Dockerfiles. This change is not
ideal because it means changes to the Dockerfile now also need to be
applied to the Dockerfile.dev but upgrading the version of docker in the
build environment is a slightly bigger task and this is blocking
deploys.
https://docs.docker.com/release-notes/docker-engine/#190-2015-11-03
=> Fix Dockerfile pre-1.9 versions of docker

courtfinder/courtfinder/settings/base.py, courtfinder/courts/views.py, courtfinder/search/templates/search/postcode.jinja, courtfinder/search/templates/search/results.jinja, courtfinder/search/views.py
Looks like the pep8 commit 8f3b9a5 accidentally broke these pages.
This addresses a reflected XSS alert marked as high risk.
See: https://cwe.mitre.org/data/definitions/79.html
Previously it was returning a 500
=> Rst 443 fix zap issues

.travis.yml, requirements/testing.txt
- print out report in travis job
- submit to code climate
- current python cc reporter needs coverage <4.4
- only submit coverage for pushes to master
=> Add code coverage report

courtfinder/search/court_search.py
Bad user input and unrecognised postcodes should not be logged in sentry
as errors, filling up the log
=> RST-577 Reduce mapit 40x error logging

courtfinder/assets-src/javascripts/admin.js
b/strong tags have no moj template styles
and the original requirement was to provide links anyway
=> Remove formatting options
