hmcts/courtfinder-search

courtfinder/search/views.py

Copy change for Forced Marriage area of law to include FGM as well.

FGM copy change

---

requirements/base.txt

this was deemed an important security update on other projects, so makes sense to do here too

updated Django to latest 1.7

---

courtfinder/search/rules.py
data/courts.json
data/test_data/areas_of_law.json

see [courtfinder-search/86](https://github.com/ministryofjustice/courtfinder-search/pull/86)

test data / fixture updated to work with updated FGM copy in areas of law

---

shippable.yml

upgrading Shippable node.js in the hope that `npm install` works better

shippable npm install fix

---

courtfinder/core/utils.py
courtfinder/courts/views.py
courtfinder/search/court_search.py
courtfinder/search/ingest.py
courtfinder/search/management/commands/populate-db.py
courtfinder/search/migrations/0007_areaoflaw_slug.py
courtfinder/search/models.py
courtfinder/search/rules.py
courtfinder/search/templates/search/aol.jinja
courtfinder/search/tests/test_api.py
courtfinder/search/tests/test_pages.py
courtfinder/search/tests/test_search.py
courtfinder/search/views.py
courtfinder/staticpages/templates/staticpages/api.jinja
data/test_data/courts.json

previously, changing a name of an "area of law" in the admin app caused the area of law selection to raise a 500. also, now using slugs instead of names for areas of law in the hope they are modified less often.

area of law flexibility

---

courtfinder/courtfinder/settings/base.py

The auth token and timeout settings had the wrong names, they should be
POSTCODEINFO_AUTH_TOKEN and POSTCODEINFO_TIMEOUT, respectively

Fix postcodeinfo settings

---

courtfinder/settings/base.py

Changed logging handlers to use stdout & modified loggers to use them.

---

courtfinder/apps/search/management/commands/populate-db.py
data/import-utilities/ingest-json.sh
requirements/base.txt

* Add boto3 to requirements
* Update script to connect to S3 through boto3
* Use logging

Fix populate database script

---

Dockerfile
run.sh

Update the run script so that migrate, seed, and create tasks can
be passed through the DOCKER_STATE environment variable.

Standardise the run script

---

courtfinder/apps/search/management/commands/populate-db.py

* Make it simpler for the script to compare whether files
have changed after calling a download
* Make sure DataStatus is always updated when we import files

Simplify populate-db checking of file change

---

courtfinder/settings/base.py
courtfinder/settings/production.py
courtfinder/settings/staging.py

This change removes all the handcoded passwords from the project,
only the environment variable DB_PASSWORD is used.

Remove all default passwords

---

courtfinder/apps/courts/templates/courts/court.jinja
courtfinder/apps/courts/views.py

https://staging.courttribunalfinder.service.gov.uk/courts/aardvaark
(Closes #120)

Create courts image link to s3 bucket from environment variable

---

courtfinder/search/models.py

Apply alphanumeric ordering to the AOL list

Apply ordering to area of law list

---

courtfinder/courtfinder/settings/base.py
courtfinder/courtfinder/settings/production.py
courtfinder/courtfinder/settings/staging.py
courtfinder/courtfinder/urls.py
courtfinder/healthcheck/healthchecks.py
courtfinder/healthcheck/urls.py
courtfinder/healthcheck/views.py
requirements/base.txt

Cherry picked two commits from master to add the django irat healthcheck and ping endpoints.
The ping.json endpoint currently shows null for each value, but should show the correct commit information when deployed via jenkins.  This needs testing after a merge.
Also the healthcheck endpoint currently shows an error for a test url when testing on local dev - but this should also clear up when testing on staging or prod, due to the values added to bottom of courtfinder/settings/staging.py and courtfinder/settings/production.py

Add ping and healthcheck

---

courtfinder/courtfinder/brake_config.py
courtfinder/courtfinder/settings/base.py
courtfinder/staticpages/views.py

The rate limiter was using the ELB IP address and thus not working correctly. This should fix it.

Make sure rate limiter uses X-fowarded-for IP, not the ELB IP

---

courtfinder/assets-src/stylesheets/styles.scss

The asset exists at /assets/images/icon-pointer-2x.png

Fix path to icon-pointer-2x.png

---

courtfinder/courts/templates/courts/court.jinja
courtfinder/courts/views.py
courtfinder/search/migrations/0007_auto_20161102_1505.py
courtfinder/search/models.py

This allows null values in the facilities.description field, which should resolve the issues the admin data ingest process.

Allow null values for facility.description field

---

courtfinder/search/views.py

Prevent mismatches from DB and code AOL lists from causing errors

Fix AOL error

---

courtfinder/assets-src/stylesheets/styles.scss
courtfinder/courts/templates/courts/court.jinja
courtfinder/courts/views.py
courtfinder/search/court_search.py
courtfinder/search/migrations/0008_auto_20170111_1101.py
courtfinder/search/models.py
courtfinder/search/templates/search/courtcode.jinja
courtfinder/search/templates/search/index.jinja
courtfinder/search/templates/search/results.jinja
courtfinder/search/tests/test_courtcode.py
courtfinder/search/tests/test_search.py
courtfinder/search/urls.py
courtfinder/search/views.py
data/test_data/courts.json

Contains a model update.
Discovery phase changes - DX number moved, Court code search added, Areas of Law external URL added and breadcrumbs updated.
DX number - The 'Legal professionals' block has been removed and the DX number and court number moved to the 'Visit Us' block.
Court code - A new search option has been added to allow users to search specifically on the court number; breadcrumbs have also been updated.
AoL - Links have been applied to these with external links to Government sites. This involves a model update!
Breadcrumbs - The 'Court list' crumb has been changed to 'A-Z list of all courts'

CGI discovery phase changes

---

courtfinder/search/templates/search/spoe.jinja
courtfinder/search/tests/test_search.py
courtfinder/search/urls.py
courtfinder/search/views.py

If it's a new issue then go to postcode search, existing cases should go to a-z list of courts.

Changes to Divorce & Children AoL pages.

---

courtfinder/courts/templates/courts/court.jinja
courtfinder/search/templates/search/courtcode.jinja
courtfinder/search/templates/search/index.jinja
courtfinder/search/templates/search/results.jinja

CF-112 Update 'Court code' to 'Court location code'

---

courtfinder/assets-src/stylesheets/styles.scss
courtfinder/courts/templates/courts/court.jinja
courtfinder/courts/tests.py
courtfinder/courts/views.py
courtfinder/search/ingest.py
courtfinder/search/migrations/0011_contact_explanation.py
courtfinder/search/models.py
courtfinder/search/tests/test_search.py
data/test_data/courts.json

1 migration included.
Tests included.
Updated Ingest file.
This PR is part 1 of a 2 part change for CF-30. Part 2: Admin functionality is WIP.

Add explanation to court phone numbers and changed styling

---

Dockerfile
requirements/base.txt

@richerry this builds on my local machine, but I haven't actually tested that the app works.

Bump requests version to 2.7.0 with security

---

courtfinder/search/court_search.py

Removed: workaround for mapit ssl issue

Removed: workaround for mapit ssl issue

---

courtfinder/search/rules.py
courtfinder/search/templates/search/postcode.jinja
courtfinder/search/templates/search/spoe.jinja
courtfinder/search/views.py

Civil partnership search now points to the same place as divorce area of law

Amend 'Civil partnership' to 'Divorce' search

---

courtfinder/courts/templates/courts/court.jinja
courtfinder/search/templates/search/results.jinja

No Migrations.
No tests.
Changes as per CF-115/CF-116 add tooltips to links

CF-115/CF-116 Add tooltips to links

---

courtfinder/search/templates/search/postcode.jinja
courtfinder/search/templates/search/results.jinja
courtfinder/search/templates/search/spoe.jinja
courtfinder/search/tests/test_search.py
data/test_data/courts.json

No Migrations.
Tests included.

CF-117 Money Claims Postcode Search Option

---

Dockerfile
courtfinder/courts/tests.py
data/test_data/courts.json
requirements/testing.txt

After some discussion it was agreed that lxml and cssselect would make for better tests. This is the first test using these tools.

Added test for facility icons

---

Dockerfile

When reverting the dockerfile I did not revert back to before the feature branch started. This PR fixed that.

Fixed: Further reverted Dockerfile to correct version

---

courtfinder/courtfinder/settings/staging.py

This is failing because it isn't integrated with Travis yet.

Enable Leaflets on staging

---

courtfinder/search/ingest.py

Tolerate null values for attributes alongside missing attributes consistently in the ingest script. Treat them the same as empty strings.

Fixed: RST-208 - Fix sync script

---

cucumber/features/area_of_law_page.feature
cucumber/features/search_results_page.feature
cucumber/features/step_definitions/area_of_law_page_steps.rb
cucumber/features/step_definitions/search_results_page_steps.rb
cucumber/features/support/capybara_driver_helper.rb
cucumber/features/support/page_objects/search_results_page.rb

[JIRA ticket](https://triadmoj.atlassian.net/browse/RST-221)
Changed the capybara_driver_helper.rb to run tests locally.
Updated tests to match new data, tests are passing.

RST-221 Run Cucumber tests on a testing environment

---

courtfinder/search/tests/test_search.py
courtfinder/search/views.py
data/test_data/courts.json

Add a description for the 'High Court District Registry' area of law.

RST-233 Add area of law description

---

cucumber/features/search_results_page.feature
cucumber/features/step_definitions/search_results_page_steps.rb
cucumber/features/support/page_objects/search_results_page.rb

This is just to finish the testing for this page https://courttribunalfinder.service.gov.uk/search/results?aol=All&postcode=ig1+2bn

Cucumber tests for CTF search results page

---

cucumber/features/step_definitions/search_page_steps.rb

Small addition to the current test that checks that the options on the search page have radio buttons

added radio type button for search page

---

cucumber/features/name_or_address_page.feature
cucumber/features/step_definitions/name_or_address_steps.rb
cucumber/features/support/page_objects/name_or_address_page.rb

Cucumber tests for this page https://courttribunalfinder.service.gov.uk/search/address

Added cucumber tests for search by name or address

---

.gitignore
cucumber/features/all_courts_page.feature
cucumber/features/step_definitions/all_courts_page_steps.rb
cucumber/features/step_definitions/name_or_address_steps.rb
cucumber/features/support/page_objects/all_courts_page.rb

Added tests for A-Z list of all courts page
Added screenshots to git ignore
Updated args on name or address page

Tests for search all courts page

---

cucumber/features/court_code_page.feature
cucumber/features/step_definitions/court_code_page_steps.rb
cucumber/features/support/capybara_driver_helper.rb
cucumber/features/support/page_objects/court_code_page.rb

https://courttribunalfinder.service.gov.uk/search/courtcode

Cucumber tests for search by court location code page

---

cucumber/features/navigation.feature
cucumber/features/step_definitions/navigation_steps.rb
cucumber/features/support/page_objects/base_page.rb
cucumber/features/support/page_objects/navigation_page.rb

Global header
Breadcrumbs
Beta 
Give your feedback

Added Cucumber tests for navigation

---

courtfinder/courts/templates/courts/court.jinja
courtfinder/courts/tests.py
courtfinder/search/ingest.py
courtfinder/search/migrations/0016_courtopeningtime_sort.py
courtfinder/search/models.py
courtfinder/search/templatetags/courttags.py
courtfinder/search/tests/test_search.py
data/test_data/courts.json

The import script will now contain a sort key and value for opening times. This PR adds the sorting of opening times to the public app.

Added: sorting to opening times

---

cucumber/features/step_definitions/court_code_page_steps.rb

@robyoung this is the PR to update the test for the fix on RST-260

RST-260 updated string to match fix

---

.travis.yml

Run gulp from the node modules path rather than trying to install it globally.

Fix travis for current image

---

apt/base.sh

Add the postgresql-client package as this provides psql and is required
by the courts import script.

Add postgresql-client

---

courtfinder/assets-src/stylesheets/styles.scss
courtfinder/courts/templates/courts/court.jinja

- tweaked styles to make the section look better
- renamed heading

RST-568 Move court information higher on the page

---

apt/base.sh

**Remove postgis and postgresql-client from container**

Remove postgis and postgresql-client from container

---

courtfinder/search/court_search.py

- remove non failures logged as errors
- remove mappit exceptions logged twice

Clean up sentry logging

---

courtfinder/admin/forms.py
courtfinder/admin/templates/court.jinja
courtfinder/admin/templates/court_address.jinja
courtfinder/admin/templates/court_location.jinja
courtfinder/admin/urls.py
courtfinder/admin/views.py
courtfinder/assets-src/stylesheets/admin.scss
courtfinder/geolocation/mapit.py
courtfinder/geolocation/test/test_mapit.py
courtfinder/search/models.py
features/edit_location.feature
requirements/base.txt

reusable mapit lib to use for postcode mapping
the existing mapit code isn't reusable

geolocation library

---

courtfinder/admin/forms.py
courtfinder/admin/templates/court/postcodes.html
courtfinder/admin/views.py
courtfinder/assets-src/javascripts/admin.js

- don't allow partial postcodes
- warning about deleting postcodes

Postcode management feedback, partial codes, UI

---

data/import-utilities/ingest-json.sh

- make sure import job doesn't run after migration
- allow to override it in case of early deployment

Disable import job

---

performance-tests/.gitignore
performance-tests/Dockerfile
performance-tests/README.md
performance-tests/gatling.sh
performance-tests/src/test/resources/application.conf
performance-tests/src/test/scala/simulations/HttpConfiguration.scala
performance-tests/src/test/scala/simulations/PublicPerformance.scala
performance-tests/src/test/scala/simulations/StaffPerformance.scala

Performance tests

---

.dockerignore
README.md
azure-pipelines.yml

refactor for CI build and readme update
```
[ ] Yes
[x] No
```

refactor and readme update

---

Dockerfile
pipeline-steps/docker-build-manual.yaml
pipeline-steps/docker-build-release.yaml
pipeline-steps/docker-build.yaml

changing variable name to APP_VERSION
```
[ ] Yes
[x] No
```

changing variable name to APP_VERSION

---

courtfinder/locale/cy/LC_MESSAGES/django.po
courtfinder/locale/en/LC_MESSAGES/django.po
courtfinder/search/rules.py
courtfinder/search/templates/search/postcode.jinja
courtfinder/search/views.py

Present jurisdiction error when user types in scottish postcode in Children AOL

RST-2459-blockScottishPostcodesForChildrenAol

---

.travis.yml

updated chromedriver
```
[ ] Yes
[ ] No
```

RST-2486/Upgrade-chrome-driver

---

.travis.yml

Upgraded chromedriver 80

---

courtfinder/courts/templates/courts/court.jinja
courtfinder/locale/cy/LC_MESSAGES/django.po
courtfinder/locale/en/LC_MESSAGES/django.po

Rst 2484/add coming to court link

---

requirements/base.txt

upgraded markupsafe

---

requirements/base.txt

upgraded django and pillow

---

courtfinder/search/rules.py

Removed TD from scottish postcodes

---

courtfinder/admin/views.py

Added Facilities to csv export

---

.travis.yml
courtfinder/courts/templates/courts/court.jinja
courtfinder/locale/cy/LC_MESSAGES/django.po
courtfinder/locale/en/LC_MESSAGES/django.po

Changed additional Information title to Covid-19 title

---

.travis.yml
courtfinder/assets-src/javascripts/admin.js
courtfinder/assets-src/stylesheets/styles.scss

- enable bold italic and underline
- restore bold font formatting

Add basic formatting options to additional information

---

courtfinder/admin/views.py

add court types and court codes to csv export

---

courtfinder/admin/forms.py
features/edit_basic.feature

remove updating of slug when name is updated

---

requirements/base.txt

upgrade django to 1.11.29

---

run.sh

enable threads on uwsgi
